-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"post_id" uuid NOT NULL,
	"password_hash" text,
	"content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"like_count" integer DEFAULT 0 NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "comments_content_length" CHECK (char_length(content) <= 3000)
);
--> statement-breakpoint
ALTER TABLE "comments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "series" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "series_description_length" CHECK (char_length(description) <= 500),
	CONSTRAINT "series_title_check" CHECK (char_length(title) <= 100)
);
--> statement-breakpoint
ALTER TABLE "series" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tags" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"post_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "tags_name_key" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "tags" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nickname" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	"auth_user_id" uuid,
	"registered_at" timestamp with time zone,
	"profile_image_url" text,
	"bio" text,
	"subscriber_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "users_bio_length_check" CHECK ((bio IS NULL) OR (char_length(bio) <= 200)),
	CONSTRAINT "users_nickname_length_check" CHECK ((char_length(nickname) >= 1) AND (char_length(nickname) <= 50))
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "milestone_thresholds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" text NOT NULL,
	"threshold" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "milestone_thresholds_type_threshold_key" UNIQUE("type","threshold"),
	CONSTRAINT "milestone_thresholds_type_check" CHECK (type = ANY (ARRAY['post_view'::text, 'post_like'::text, 'comment_like'::text, 'subscriber'::text]))
);
--> statement-breakpoint
ALTER TABLE "milestone_thresholds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"type" text NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL,
	"post_id" uuid,
	"comment_id" bigint,
	"comment_count" integer,
	"representative_user_id" uuid,
	"representative_comment_id" bigint,
	"milestone_value" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"inquiry_thread_id" uuid,
	CONSTRAINT "chk_comment_fields" CHECK ((type <> 'comment'::text) OR ((post_id IS NOT NULL) AND (comment_count IS NOT NULL))),
	CONSTRAINT "chk_comment_like_fields" CHECK ((type <> 'comment_like_milestone'::text) OR ((comment_id IS NOT NULL) AND (milestone_value IS NOT NULL))),
	CONSTRAINT "chk_inquiry_reply_fields" CHECK ((type <> 'inquiry_reply'::text) OR (inquiry_thread_id IS NOT NULL)),
	CONSTRAINT "chk_post_milestone_fields" CHECK ((type <> ALL (ARRAY['post_view_milestone'::text, 'post_like_milestone'::text])) OR ((post_id IS NOT NULL) AND (milestone_value IS NOT NULL))),
	CONSTRAINT "chk_subscriber_fields" CHECK ((type <> 'subscriber_milestone'::text) OR (milestone_value IS NOT NULL)),
	CONSTRAINT "notifications_type_check" CHECK (type = ANY (ARRAY['comment'::text, 'post_view_milestone'::text, 'post_like_milestone'::text, 'comment_like_milestone'::text, 'subscriber_milestone'::text, 'inquiry_reply'::text]))
);
--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "outreach_emails" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"creator_id" uuid NOT NULL,
	"gmail_thread_id" text,
	"gmail_message_id" text,
	"direction" text NOT NULL,
	"subject" text NOT NULL,
	"body" text NOT NULL,
	"sent_at" timestamp with time zone NOT NULL,
	"message_id" text,
	"is_read" boolean DEFAULT false NOT NULL,
	CONSTRAINT "outreach_emails_gmail_message_id_unique" UNIQUE("gmail_message_id")
);
--> statement-breakpoint
ALTER TABLE "outreach_emails" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tags" text[] NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"title" text NOT NULL,
	"password_hash" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"user_id" uuid NOT NULL,
	"series_id" uuid,
	"series_order" integer,
	"visibility" text DEFAULT 'public' NOT NULL,
	"content_json" jsonb NOT NULL,
	"preview" text NOT NULL,
	"content_text" text NOT NULL,
	CONSTRAINT "posts_title_check" CHECK (char_length(title) <= 100),
	CONSTRAINT "posts_visibility_check" CHECK (visibility = ANY (ARRAY['public'::text, 'unlisted'::text, 'private'::text]))
);
--> statement-breakpoint
ALTER TABLE "posts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "post_stats" (
	"post_id" uuid PRIMARY KEY NOT NULL,
	"like_count" integer DEFAULT 0 NOT NULL,
	"view_count" integer DEFAULT 0 NOT NULL,
	"comment_count" integer DEFAULT 0 NOT NULL,
	"avg_read_time" numeric DEFAULT '0' NOT NULL,
	"popularity" numeric DEFAULT '0' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "post_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "post_views" (
	"user_id" uuid NOT NULL,
	"post_id" uuid NOT NULL,
	"read_duration" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "post_views" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "gmail_tokens" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "gmail_tokens" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "drafts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"post_id" uuid,
	"title" text DEFAULT '' NOT NULL,
	"content_json" jsonb,
	"tags" text[] DEFAULT '{""}' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "drafts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "media" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"size_bytes" integer NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"url" text,
	"type" text DEFAULT 'image' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "media" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "creators" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"channel_name" text NOT NULL,
	"email" text NOT NULL,
	"memo" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_mailed_at" timestamp with time zone,
	"user_id" uuid
);
--> statement-breakpoint
ALTER TABLE "creators" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "inquiry_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"thread_id" uuid NOT NULL,
	"sender_type" text NOT NULL,
	"sender_id" uuid NOT NULL,
	"content" text NOT NULL,
	"images" uuid[] DEFAULT '{""}',
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "inquiry_messages_sender_type_check" CHECK (sender_type = ANY (ARRAY['USER'::text, 'ADMIN'::text]))
);
--> statement-breakpoint
ALTER TABLE "inquiry_messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "inquiry_threads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"status" text DEFAULT 'AWAITING_REPLY' NOT NULL,
	"status_changed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_message_preview" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"last_message_id" uuid,
	"first_message_preview" text,
	"first_message_id" uuid,
	"user_unread_count" integer DEFAULT 0 NOT NULL,
	"admin_unread_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "inquiry_threads_status_check" CHECK (status = ANY (ARRAY['AWAITING_REPLY'::text, 'ANSWERED'::text, 'CLOSED'::text]))
);
--> statement-breakpoint
ALTER TABLE "inquiry_threads" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "posts_v2" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tags" text[] NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"title" text NOT NULL,
	"password_hash" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"user_id" uuid NOT NULL,
	"series_id" uuid,
	"series_order" integer,
	"visibility" text DEFAULT 'public' NOT NULL,
	"content_json" jsonb NOT NULL,
	"preview" text NOT NULL,
	"content_text" text NOT NULL,
	CONSTRAINT "posts_title_check" CHECK (char_length(title) <= 100),
	CONSTRAINT "posts_visibility_check" CHECK (visibility = ANY (ARRAY['public'::text, 'unlisted'::text, 'private'::text]))
);
--> statement-breakpoint
ALTER TABLE "posts_v2" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "media_variants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"media_id" uuid NOT NULL,
	"variant" text,
	"url" text NOT NULL,
	"description" text,
	"width" integer,
	"height" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"type" text DEFAULT 'image' NOT NULL,
	CONSTRAINT "media_variants_type_check" CHECK (type = ANY (ARRAY['image'::text, 'audio'::text])),
	CONSTRAINT "media_variants_variant_check" CHECK (((type = 'image'::text) AND (variant = ANY (ARRAY['small'::text, 'medium'::text, 'original'::text]))) OR ((type = 'audio'::text) AND (variant IS NULL)))
);
--> statement-breakpoint
ALTER TABLE "media_variants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "media_v2" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"size_bytes" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "media_v2" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users_v2" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nickname" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	"auth_user_id" uuid,
	"registered_at" timestamp with time zone,
	"bio" text,
	"subscriber_count" integer DEFAULT 0 NOT NULL,
	"profile_image_id" uuid,
	CONSTRAINT "users_bio_length_check" CHECK ((bio IS NULL) OR (char_length(bio) <= 200)),
	CONSTRAINT "users_nickname_length_check" CHECK ((char_length(nickname) >= 1) AND (char_length(nickname) <= 50))
);
--> statement-breakpoint
ALTER TABLE "users_v2" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "subscriptions" (
	"follower_id" uuid NOT NULL,
	"following_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "subscriptions_pkey" PRIMARY KEY("follower_id","following_id"),
	CONSTRAINT "subscriptions_no_self_follow" CHECK (follower_id <> following_id)
);
--> statement-breakpoint
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "post_likes" (
	"user_id" uuid NOT NULL,
	"post_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "post_likes_pkey" PRIMARY KEY("user_id","post_id")
);
--> statement-breakpoint
ALTER TABLE "post_likes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "post_skips" (
	"user_id" uuid NOT NULL,
	"post_id" uuid NOT NULL,
	"skip_count" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "post_skips_pkey" PRIMARY KEY("user_id","post_id")
);
--> statement-breakpoint
ALTER TABLE "post_skips" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "next_auth"."users"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "public"."comments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_inquiry_thread_id_fkey" FOREIGN KEY ("inquiry_thread_id") REFERENCES "public"."inquiry_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_representative_comment_id_fkey" FOREIGN KEY ("representative_comment_id") REFERENCES "public"."comments"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_representative_user_id_fkey" FOREIGN KEY ("representative_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outreach_emails" ADD CONSTRAINT "outreach_emails_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "public"."creators"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_series_id_fkey" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "post_stats" ADD CONSTRAINT "post_stats_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "post_views" ADD CONSTRAINT "post_views_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "post_views" ADD CONSTRAINT "post_views_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "drafts" ADD CONSTRAINT "post_drafts_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "drafts" ADD CONSTRAINT "post_drafts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "media" ADD CONSTRAINT "media_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "creators" ADD CONSTRAINT "creators_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inquiry_messages" ADD CONSTRAINT "inquiry_messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "inquiry_messages" ADD CONSTRAINT "inquiry_messages_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "public"."inquiry_threads"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "inquiry_threads" ADD CONSTRAINT "inquiry_threads_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "posts_v2" ADD CONSTRAINT "posts_v2_series_id_fkey" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "posts_v2" ADD CONSTRAINT "posts_v2_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "media_variants" ADD CONSTRAINT "media_variants_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "public"."media_v2"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_v2" ADD CONSTRAINT "media_v2_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users_v2" ADD CONSTRAINT "users_v2_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "next_auth"."users"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users_v2" ADD CONSTRAINT "users_v2_profile_image_id_fkey" FOREIGN KEY ("profile_image_id") REFERENCES "public"."media_v2"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_follower_id_fkey" FOREIGN KEY ("follower_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_following_id_fkey" FOREIGN KEY ("following_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "post_skips" ADD CONSTRAINT "post_skips_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "post_skips" ADD CONSTRAINT "post_skips_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "idx_comments_post_id" ON "comments" USING btree ("post_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_comments_user_id" ON "comments" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_series_user_id" ON "series" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_tags_name_trgm" ON "tags" USING gin ("name" gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "users_nickname_unique" ON "users" USING btree ("nickname" text_ops) WHERE (deleted_at IS NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "idx_notifications_comment_milestone_unique" ON "notifications" USING btree ("comment_id" int4_ops,"type" text_ops,"milestone_value" int4_ops) WHERE (type = 'comment_like_milestone'::text);--> statement-breakpoint
CREATE UNIQUE INDEX "idx_notifications_comment_upsert" ON "notifications" USING btree ("post_id" uuid_ops,"type" uuid_ops) WHERE ((type = 'comment'::text) AND (is_read = false));--> statement-breakpoint
CREATE UNIQUE INDEX "idx_notifications_inquiry_reply_upsert" ON "notifications" USING btree ("inquiry_thread_id" text_ops,"type" text_ops) WHERE ((type = 'inquiry_reply'::text) AND (is_read = false));--> statement-breakpoint
CREATE UNIQUE INDEX "idx_notifications_post_milestone_unique" ON "notifications" USING btree ("post_id" int4_ops,"type" text_ops,"milestone_value" text_ops) WHERE (type = ANY (ARRAY['post_view_milestone'::text, 'post_like_milestone'::text]));--> statement-breakpoint
CREATE UNIQUE INDEX "idx_notifications_subscriber_milestone_unique" ON "notifications" USING btree ("user_id" uuid_ops,"type" uuid_ops,"milestone_value" int4_ops) WHERE (type = 'subscriber_milestone'::text);--> statement-breakpoint
CREATE INDEX "idx_notifications_user_unread" ON "notifications" USING btree ("user_id" uuid_ops) WHERE (is_read = false);--> statement-breakpoint
CREATE INDEX "idx_notifications_user_updated" ON "notifications" USING btree ("user_id" uuid_ops,"updated_at" timestamptz_ops,"id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_posts_created_at" ON "posts" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_posts_series_id" ON "posts" USING btree ("series_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_posts_series_order" ON "posts" USING btree ("series_id" int4_ops,"series_order" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_posts_tags" ON "posts" USING gin ("tags" array_ops);--> statement-breakpoint
CREATE INDEX "idx_posts_tags_trgm" ON "posts" USING gin (immutable_array_to_string(tags, ' '::text) gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_posts_title_trgm" ON "posts" USING gin ("title" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_posts_user_id" ON "posts" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_posts_visibility" ON "posts" USING btree ("visibility" text_ops);--> statement-breakpoint
CREATE INDEX "idx_post_stats_popularity" ON "post_stats" USING btree ("popularity" numeric_ops);--> statement-breakpoint
CREATE INDEX "idx_post_views_post_id" ON "post_views" USING btree ("post_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_post_views_user_id" ON "post_views" USING btree ("user_id" timestamptz_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_post_drafts_user_id" ON "drafts" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_media_user_id" ON "media" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "creators_user_id_idx" ON "creators" USING btree ("user_id" uuid_ops) WHERE (user_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "idx_inquiry_messages_thread" ON "inquiry_messages" USING btree ("thread_id" timestamptz_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_inquiry_threads_auto_close" ON "inquiry_threads" USING btree ("status_changed_at" timestamptz_ops) WHERE ((status = 'ANSWERED'::text) AND (is_deleted = false));--> statement-breakpoint
CREATE INDEX "idx_inquiry_threads_user" ON "inquiry_threads" USING btree ("user_id" timestamptz_ops,"updated_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "posts_v2_author_id_idx" ON "posts_v2" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "posts_v2_created_at_idx" ON "posts_v2" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "posts_v2_immutable_array_to_string_idx" ON "posts_v2" USING gin (immutable_array_to_string(tags, ' '::text) gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "posts_v2_series_id_idx" ON "posts_v2" USING btree ("series_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "posts_v2_series_id_series_order_idx" ON "posts_v2" USING btree ("series_id" int4_ops,"series_order" int4_ops);--> statement-breakpoint
CREATE INDEX "posts_v2_tags_idx" ON "posts_v2" USING gin ("tags" array_ops);--> statement-breakpoint
CREATE INDEX "posts_v2_title_idx" ON "posts_v2" USING gin ("title" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "posts_v2_visibility_idx" ON "posts_v2" USING btree ("visibility" text_ops);--> statement-breakpoint
CREATE INDEX "idx_media_variants_media_id" ON "media_variants" USING btree ("media_id" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "media_variants_audio_unique" ON "media_variants" USING btree ("media_id" uuid_ops) WHERE (type = 'audio'::text);--> statement-breakpoint
CREATE UNIQUE INDEX "media_variants_image_unique" ON "media_variants" USING btree ("media_id" uuid_ops,"variant" text_ops) WHERE (type = 'image'::text);--> statement-breakpoint
CREATE INDEX "media_v2_user_id_idx" ON "media_v2" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "users_v2_nickname_idx" ON "users_v2" USING btree ("nickname" text_ops) WHERE (deleted_at IS NULL);--> statement-breakpoint
CREATE INDEX "idx_subscriptions_following" ON "subscriptions" USING btree ("following_id" uuid_ops);--> statement-breakpoint
CREATE POLICY "Block all access" ON "comments" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "series" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "tags" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "users" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "milestone_thresholds" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "notifications" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "outreach_emails" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "posts" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "post_stats" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "post_views" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "gmail_tokens" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "drafts" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "media" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "creators" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "inquiry_messages" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "inquiry_threads" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "posts_v2" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "media_variants" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "media_v2" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "users_v2" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "subscriptions" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "post_likes" AS PERMISSIVE FOR ALL TO public USING (false);--> statement-breakpoint
CREATE POLICY "Block all access" ON "post_skips" AS PERMISSIVE FOR ALL TO public USING (false);
*/