export const ErrorCode = {
  DUPLICATE_NICKNAME: 'DUPLICATE_NICKNAME',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  POST_FORBIDDEN: 'POST_FORBIDDEN',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DAILY_QUOTA_EXHAUSTED: 'DAILY_QUOTA_EXHAUSTED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
